/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;

import static io.restassured.RestAssured.*;
import static org.junit.jupiter.api.Assertions.*;
import static org.hamcrest.Matchers.*;

class JsonPlaceholderTest {
    @Test
    public void getExistingPost() {
    }

    @Test
    public void createPost() {
    }
}
